{% set name = "bcpandas" %}
{% set version = "2.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 723b60b3440f58cbe38d7bede8c4f888cb839a7f7f22dd34deb25d83f3eacbb3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8.1
    - pip
    - setuptools
    - poetry >=1.3.2
  run:
    - python >=3.8.1
    - pandas >=0.19
    - pyodbc
    - sqlalchemy >=1.0,<2

test:
  requires:
    - pip
  imports:
    - bcpandas

about:
  home: https://pypi.org/project/bcpandas
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Wrapper around BCP to transfer data between pandas and SQL Server.
  description: |
    High-level wrapper around BCP for high performance data transfers between pandas and SQL Server. 
    No knowledge of BCP required!!
  doc_url: https://github.com/yehoshuadimarsky/bcpandas
  dev_url: https://github.com/yehoshuadimarsky/bcpandas

extra:
  recipe-maintainers:
    - borchero
    - yehoshuadimarsky
    - owenlamont
