{% set name = "bcpandas" %}
{% set version = "2.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab0e8cba5ffdedf6ae3561f4b4e29702bf4821ca3d5d7770e82df87e671093d6

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - poetry >=1.3.2
  run:
    - python >={{ python_min }}
    - pandas >=1.5
    - pyodbc
    - sqlalchemy >=1.4

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - bcpandas

about:
  home: https://pypi.org/project/bcpandas
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Wrapper around BCP to transfer data between pandas and SQL Server.
  description: |
    High-level wrapper around BCP for high performance data transfers between pandas and SQL Server. 
    No knowledge of BCP required!!
  doc_url: https://github.com/yehoshuadimarsky/bcpandas
  dev_url: https://github.com/yehoshuadimarsky/bcpandas

extra:
  recipe-maintainers:
    - borchero
    - yehoshuadimarsky
    - owenlamont
